# -*- coding: utf8 -*-
import numpy as np
import scipy.linalg as lin
import Levenshtein as leven
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.cluster import AffinityPropagation
import itertools

l = [["http://fecamp-services.com/plombier-paris/depannage", "bon plombier paris"],
["sos plombier 92", "http://www.sos-plombier-discount.fr/"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier sanitaire"],
["plomberie depannage", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier à", "http://www.zeplombier.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "depannage de plomberie"],
["plombier de paris", "http://www.plombierparis-75.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "urgences plomberie"],
["plomberie formation", "http://www.jcomjeune.com/article-metier/plombier"],
["salaire artisan plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "installation sanitaire plomberie"],
["artisan plomberie", "http://berthier-plombier.fr/"],
["http://www.plombier-toulouse-ath.com/", "plomberie toulouse"],
["http://www.jcomjeune.com/article-metier/plombier", "plomberie formation"],
["http://www.jcomjeune.com/article-metier/plombier", "définition de plombier"],
["depannage de plomberie", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.urgence-plombier-electricien.fr/", "sos plomberie paris"],
["depannage plomberie", "http://www.urgence-plombier-electricien.fr/"],
["http://www.sos-plombier-discount.fr/", "plomberie ile de france"],
["plombier à paris", "http://www.sos-plombier-discount.fr/"],
["paris electricien", "http://www.urgence-plombier-electricien.fr/"],
["plombier de paris", "http://plombiers-paris-75.fr/"],
["http://www.plombierparis-75.com/", "plombier sur"],
["plombier a paris", "http://plombiers-paris-75.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bep plomberie"],
["http://www.sos-plombier-discount.fr/", "plombier urgence"],
["http://www.sos-plombier-discount.fr/", "depannage plomberie 92"],
["plombier paris 75", "http://plombiers-paris-75.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier formation"],
["fiche de poste plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.urgence-plombier-electricien.fr/", "sos plombier"],
["plombier d urgence paris", "http://www.urgence-plombier-electricien.fr/"],
["plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier urgence", "http://www.sos-plombier-discount.fr/"],
["http://www.pagesjaunes.fr/activites/plombier.html", "trouver un plombier"],
["http://plombiers-paris-75.fr/", "plombier a paris"],
["plombier urgence paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier paris pas cher", "http://www.plombierparis-75.com/"],
["plombier", "http://www.e-plombier.com/"],
["http://www.zeplombier.fr/", "plombier à"],
["dépannage paris", "http://www.urgence-plombier-electricien.fr/"],
["plombier pas chere", "http://fecamp-services.com/plombier-paris/depannage"],
["http://plombiers-paris-75.fr/", "plombiers"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier chauffagiste formation"],
["http://www.annuaire-plombiers.com/", "annuaire plombier"],
["paris plomberie", "http://www.plomberieparis.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "métier plombier salaire"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier 69"],
["plombier pas chere", "http://www.plombierparis-75.com/"],
["urgences plomberie", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.urgence-plombier-electricien.fr/", "plombier urgence"],
["https://fr.wikipedia.org/wiki/Plombier", "travail plombier"],
["depannage plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plombier"],
["plombier prix", "http://fecamp-services.com/plombier-paris/depannage"],
["salaire d un plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.atelier-des-artisans.com/", "plomberie paris"],
["https://fr.wikipedia.org/wiki/Plombier", "plombiers"],
["http://www.urgence-plombier-electricien.fr/", "depannage plomberie"],
["plombier urgent paris", "http://www.sos-plombier-discount.fr/"],
["chauffagiste sanitaire", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.prat-plombier-chauffagiste-69.com/", "chauffagiste a"],
["formation plomberie sanitaire", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier dordogne", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier 75", "http://plombiers-paris-75.fr/"],
["https://fr.wikipedia.org/wiki/Plombier", "définition de plombier"],
["etude de plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["tarif plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["métier de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["metier plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["plombier sur paris", "http://www.sos-plombier-discount.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier dimanche paris"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier sur"],
["http://fecamp-services.com/plombier-paris/depannage", "artisan plombier paris 12"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche metier plombier"],
["urgence plomberie", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier sanitair"],
["paris plomberie", "http://www.plombierparis-75.com/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "devenir plombier 40 ans"],
["http://www.jcomjeune.com/article-metier/plombier", "diplome de plombier"],
["installation sanitaire plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier de paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie lyon"],
["http://plombiers-paris-75.fr/", "depannage plomberie paris"],
["dépannage plomberie paris", "http://www.atelier-des-artisans.com/"],
["http://berthier-plombier-issy-les-moulineaux-92130.fr/", "plombier"],
["http://plombiers-paris-75.fr/", "plombier paris 75"],
["cap de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier de nuit", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "etude plomberie"],
["urgence plombier paris", "http://www.urgence-plombier-electricien.fr/"],
["http://plombiers-paris-75.fr/", "dépannage plomberie paris"],
["plombier professionnel", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier a paris", "http://www.plomberieparis.fr/"],
["http://www.atelier-des-artisans.com/", "plombier depannage paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier dans paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "métier plombier"],
["plombier sanitair", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.e-plombier.com/", "plombier"],
["plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "un plombier"],
["formation plombier sanitaire", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier d urgence", "http://www.sos-plombier-discount.fr/"],
["plomberie chauffagiste", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://www.prat-plombier-chauffagiste-69.com/", "plomberie chauffagiste"],
["http://www.jcomjeune.com/article-metier/plombier", "metier plomberie"],
["installation sanitaire plomberie", "https://fr.wikipedia.org/wiki/Plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plomberie à paris"],
["plomberie paris", "http://www.plomberieparis.fr/"],
["http://www.urgence-plombier-electricien.fr/", "plomberie dépannage"],
["http://plombiers-paris-75.fr/", "recherche plombier paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "lycée plomberie"],
["http://www.pagesjaunes.fr/activites/plombier.html", "recherche un plombier"],
["http://www.annuaire-plombiers.com/", "www.plombier.com"],
["http://www.sos-plombier-discount.fr/", "plombier à paris"],
["depannage plombier paris", "http://plombiers-paris-75.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "apprentissage plombier chauffagiste"],
["plombier paris 01", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.sos-plombier-discount.fr/", "sos plomberie paris"],
["travaux de plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["formation plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier wikipedia"],
["http://www.sos-plombier-discount.fr/", "urgence plombier paris"],
["http://fecamp-services.com/plombier-paris/depannage", "sos plomberie paris"],
["plombier", "http://www.sos-plombier-discount.fr/"],
["depannage plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["bep plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier paris 75", "http://www.plombierparis-75.com/"],
["artisan plombier paris 12", "http://plombiers-paris-75.fr/"],
["plombiers", "http://www.atelier-des-artisans.com/"],
["plombier paris 01", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "plomberie paris"],
["plombier urgence paris", "http://plombiers-paris-75.fr/"],
["dépannage plomberie paris", "http://www.sos-plombier-discount.fr/"],
["devenir plombier 40 ans", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "plomberie urgence"],
["plomberie urgence", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "travaux de plomberie paris"],
["salaire moyen plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.sos-plombier-discount.fr/", "dépannage plomberie paris"],
["http://plombiers-paris-75.fr/", "plombier à paris"],
["http://www.plombier-31.fr/", "plombier toulouse"],
["http://www.urgence-plombier-electricien.fr/", "plombier d urgence paris"],
["plombier à paris", "http://plombiers-paris-75.fr/"],
["fiche metier plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier à", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.annuaire-plombiers.com/", "plombier.fr"],
["urgence plombier paris", "http://www.sos-plombier-discount.fr/"],
["metier plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["bac pro plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier dans paris", "http://www.sos-plombier-discount.fr/"],
["plombier paris", "http://www.atelier-des-artisans.com/"],
["http://www.sos-plombier-discount.fr/", "plombier sur paris"],
["plombier dimanche", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.sos-plombier-discount.fr/", "plombier sos"],
["plombier sos", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "sos electricien paris"],
["bac pro plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plombier pgn"],
["http://www.sos-plombier-discount.fr/", "plombier urgent"],
["http://www.plombierparis-75.com/", "plombier parisien"],
["http://www.jcomjeune.com/article-metier/plombier", "le salaire d un plombier"],
["cap de plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.urgence-plombier-electricien.fr/", "sos plombier paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap de plomberie"],
["electricien urgence", "http://www.urgence-plombier-electricien.fr/"],
["plombiers paris", "http://www.plombierparis-75.com/"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire moyen plombier"],
["cfa plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["artisan plombier paris", "http://berthier-plombier.fr/"],
["plombier artisan", "http://berthier-plombier.fr/"],
["http://www.urgence-plombier-electricien.fr/", "urgences plomberie"],
["http://www.sos-plombier-discount.fr/", "plombier devis"],
["sos plomberie paris", "http://www.urgence-plombier-electricien.fr/"],
["http://www.plombierparis-75.com/", "plombier a paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plomberie lyon"],
["http://plombiers-paris-75.fr/", "plombier 75"],
["http://www.jcomjeune.com/article-metier/plombier", "ecole de plombier"],
["métier plombier chauffagiste", "https://fr.wikipedia.org/wiki/Plombier"],
["plombier pas cher paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombiers chauffagiste", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier professionnel"],
["https://fr.wikipedia.org/wiki/Plombier", "plombiers chauffagiste"],
["plomberie dépannage", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.urgence-plombier-electricien.fr/", "plombier 75"],
["http://www.pagesjaunes.fr/annuaire/voiron-38/plombiers", "plombier"],
["http://www.sos-plombier-discount.fr/", "urgence plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plombiers paris"],
["bep plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.urgence-plombier-electricien.fr/", "tarif depannage plomberie"],
["http://www.plombierparis-75.com/", "plombiers paris"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire artisan plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche de poste plombier chauffagiste"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bac pro plomberie chauffagiste"],
["plombier urgence paris", "http://www.urgence-plombier-electricien.fr/"],
["chauffagiste a", "http://www.prat-plombier-chauffagiste-69.com/"],
["dépannage plomberie paris", "http://plombiers-paris-75.fr/"],
["ecole de plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["etude plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier à paris", "http://www.plombierparis-75.com/"],
["http://plombiers-paris-75.fr/", "plombiers paris"],
["urgence plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.jcomjeune.com/article-metier/plombier", "plombier a l etranger"],
["http://plombiers-paris-75.fr/", "paris plomberie"],
["metier de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["sos plombier", "http://www.sos-plombier-discount.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier paris urgence"],
["http://www.urgence-plombier-electricien.fr/", "plombier"],
["urgence eau paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://fecamp-services.com/plombier-paris/depannage", "tarifs plombier paris"],
["ecole plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["nant plomberie", "http://www.zeplombier.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier paris 01"],
["sos plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie chauffagiste"],
["http://www.plombierparis-75.com/", "plombier paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie marseille"],
["electricien.fr", "http://www.urgence-plombier-electricien.fr/"],
["bac pro plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://plombiers-paris-75.fr/", "plombier de paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cfa plombier"],
["metier plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.plomberieparis.fr/", "plombier paris"],
["paris plomberie", "http://plombiers-paris-75.fr/"],
["http://www.atelier-des-artisans.com/", "paris depannage"],
[0, "plombier"],
["http://www.sos-plombier-discount.fr/", "urgences plomberie"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bep plombier"],
["plombiers paris", "http://fecamp-services.com/plombier-paris/depannage"],
["annuaire plombier", "http://www.pagesjaunes.fr/activites/plombier.html"],
["plombier paris 12eme", "http://fecamp-services.com/plombier-paris/depannage"],
["urgence eau paris", "http://plombiers-paris-75.fr/"],
["plombier parisien", "http://www.plombierparis-75.com/"],
["http://www.jcomjeune.com/article-metier/plombier", "formation de plomberie"],
["depannage plomberie paris", "http://plombiers-paris-75.fr/"],
["plombier a l etranger", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier d urgence", "http://fecamp-services.com/plombier-paris/depannage"],
["formation plombier toulouse", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier 75", "http://www.urgence-plombier-electricien.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "le plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "métier de plombier"],
["urgence plomberie paris", "http://plombiers-paris-75.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris urgence"],
["stage plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier 12eme"],
["http://plombiers-paris-75.fr/", "urgence eau paris"],
["sos plomberie paris", "http://www.sos-plombier-discount.fr/"],
["http://berthier-plombier.fr/", "artisan plomberie"],
["http://www.sos-plombier-discount.fr/", "tarifs plombier paris"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire d un plombier"],
["ecole plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier formation", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie paris"],
["http://plombiers-paris-75.fr/", "plombier dans paris"],
["le plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["plombier paris 75012", "http://fecamp-services.com/plombier-paris/depannage"],
["bep plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["urgence electricien paris", "http://www.urgence-plombier-electricien.fr/"],
["plombier chaufagiste", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://www.plombierparis-75.com/", "plombier de paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier prix"],
["http://www.sos-plombier-discount.fr/", "prix plombier paris"],
["plombier dimanche paris", "http://www.sos-plombier-discount.fr/"],
["urgences plomberie", "http://www.urgence-plombier-electricien.fr/"],
["plombier dans paris", "http://www.plomberieparis.fr/"],
["http://www.urgence-plombier-electricien.fr/", "sos electricien"],
["http://www.urgence-plombier-electricien.fr/", "depannage plomberie paris"],
["artisan plomberie", "http://www.atelier-des-artisans.com/"],
["plombier sur", "http://www.plombierparis-75.com/"],
["electriciens.fr", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "dépannage plomberie paris"],
["http://www.zeplombier.fr/", "nant plomberie"],
["bts plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["sos plomberie", "http://www.sos-plombier-discount.fr/"],
["electricien plombier", "http://www.urgence-plombier-electricien.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "fiche de poste plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche plomberie"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier chaufagiste"],
["http://www.atelier-des-artisans.com/", "plombier"],
["plombier toulouse", "http://www.plombier-31.fr/"],
["plombier gaz", "https://fr.wikipedia.org/wiki/Plombier"],
["depannage plombier paris", "http://www.urgence-plombier-electricien.fr/"],
["dépannage paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche de poste plombier"],
["plombier dans paris", "http://plombiers-paris-75.fr/"],
["salaire d un plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://berthier-plombier.fr/", "artisan plombier paris"],
["http://www.jcomjeune.com/article-metier/plombier", "fiche metier plombier"],
["plombier chaufagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["etude plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "ecole plomberie"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie chauffage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "profession plombier"],
["plombiers", "http://plombiers-paris-75.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier d urgence"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier à paris"],
["lycée professionnel plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["travaux plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier", 0],
["plomberie urgence", "http://www.sos-plombier-discount.fr/"],
["http://www.zeplombier.fr/", "plomberie nantes"],
["http://www.sos-plombier-discount.fr/", "sos plombier 92"],
["le plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "métier de plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plomberie sanitaire video"],
["plomberie forum", "http://www.pagesjaunes.fr/activites/plombier.html"],
["métier plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["plomberie du rhone", "http://www.prat-plombier-chauffagiste-69.com/"],
["plomberie depannage", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plombier toulouse"],
["http://www.atelier-des-artisans.com/", "artisan plombier paris"],
["profession plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["cap plomberie chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["dépannage plomberie paris", "http://www.urgence-plombier-electricien.fr/"],
["http://plombiers-paris-75.fr/", "plombier serieux paris"],
["cfa plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier 31", "http://www.plombier-31.fr/"],
["http://www.atelier-des-artisans.com/", "plombiers"],
["plombier.com", "http://www.e-plombier.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier en urgence"],
["http://www.jcomjeune.com/article-metier/plombier", "formation de plombier"],
["travail plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["plombiers", "http://www.annuaire-plombiers.com/"],
["paris depannage", "http://www.atelier-des-artisans.com/"],
["depannage plomberie paris", "http://www.atelier-des-artisans.com/"],
["plomberie ile de france", "http://www.sos-plombier-discount.fr/"],
["http://berthier-plombier.fr/", "plombier artisan"],
["http://fecamp-services.com/plombier-paris/depannage", "plomberie dépannage"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris pas cher"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "ecole de plomberie"],
["chauffagiste plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["formation plomberie marseille", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier drome"],
["plombier", "http://berthier-plombier-issy-les-moulineaux-92130.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "ecole de plomberie"],
["sos electricite", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris 12"],
["http://fecamp-services.com/plombier-paris/depannage", "urgence plomberie paris"],
["profession plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.plombierparis-75.com/", "paris plomberie"],
["http://www.plombierparis-75.com/", "plombier paris pas cher"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier à"],
["http://www.urgence-plombier-electricien.fr/", "electriciens.fr"],
["plombier paris", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris"],
["plomberie à paris", "http://plombiers-paris-75.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier service"],
["plombier sur", "http://plombiers-paris-75.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "métier plombier salaire"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plombier chauffagiste"],
["depannage plomberie paris", "http://www.urgence-plombier-electricien.fr/"],
["http://www.plomberieparis.fr/", "paris plomberie"],
["http://www.sos-plombier-discount.fr/", "tarif plombier paris"],
["outillage plombier chauffagiste", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.urgence-plombier-electricien.fr/", "depannage plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche rome plombier"],
["salaire plombier a son compte", "http://www.jcomjeune.com/article-metier/plombier"],
["meilleur plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier sur paris", "http://www.plombierparis-75.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "depannage plomberie paris"],
["http://www.jcomjeune.com/article-metier/plombier", "etude plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "formation plomberie"],
["dépannage plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "etude plombier"],
["définition de plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["formation plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.sos-plombier-discount.fr/", "sos plombier"],
["plombier serieux paris", "http://plombiers-paris-75.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier dans paris"],
["ecole de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.urgence-plombier-electricien.fr/", "plombier d urgence"],
["plombier devis", "http://www.sos-plombier-discount.fr/"],
["http://www.annuaire-plombiers.com/", "plombier.com"],
["http://www.sos-plombier-discount.fr/", "plombier dimanche paris"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plombier sur"],
["plombier paris urgence", "http://fecamp-services.com/plombier-paris/depannage"],
["electricien paris 10", "http://plombiers-paris-75.fr/"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plombier.fr"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier depannage"],
["http://plombiers-paris-75.fr/", "plombier paris"],
["plombier paris urgence", "http://www.urgence-plombier-electricien.fr/"],
["plombier d urgence paris", "http://www.sos-plombier-discount.fr/"],
["tarif depannage plomberie", "http://www.urgence-plombier-electricien.fr/"],
["plombier electricien", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cfa plombier chauffagiste"],
["http://www.jcomjeune.com/article-metier/plombier", "plombier formation"],
["stage de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "dépannage plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "dépannage plombier paris"],
["fiche metier plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris 12eme"],
["http://www.sos-plombier-discount.fr/", "dépannage plombier paris"],
["http://www.atelier-des-artisans.com/", "artisans plombiers"],
["https://fr.wikipedia.org/wiki/Plombier", "metier plombier"],
["http://www.urgence-plombier-electricien.fr/", "depannage de plomberie"],
["stage de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier", "http://plombiers-paris-75.fr/"],
["fiche metier plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["devis plombier paris", "http://www.sos-plombier-discount.fr/"],
["fiche de poste plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier dans paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier formation", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://berthier-plombier-issy-les-moulineaux-92130.fr/", "plombier issy les moulineaux"],
["salaire plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier a paris", "http://www.sos-plombier-discount.fr/"],
["http://plombiers-paris-75.fr/", "plombier"],
["plombier sur paris", "http://fecamp-services.com/plombier-paris/depannage"],
["https://fr.wikipedia.org/wiki/Plombier", "un plombier"],
["urgence plombier paris", "http://plombiers-paris-75.fr/"],
["etude plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bac pro plombier"],
["http://www.plombier-31.fr/", "plombier"],
["un plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["depannage plomberie 92", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "plombier en urgence"],
["http://www.urgence-plombier-electricien.fr/", "plombier urgent"],
["dépannage plombier paris", "http://plombiers-paris-75.fr/"],
["plombier depannage paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier rhone", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier a paris"],
["http://plombiers-paris-75.fr/", "dépannage plombier paris"],
["plombier sos", "http://www.urgence-plombier-electricien.fr/"],
["urgence plomberie paris", "http://www.urgence-plombier-electricien.fr/"],
["plombier de paris", "http://www.sos-plombier-discount.fr/"],
["http://www.sos-plombier-discount.fr/", "paris plomberie"],
["formation plomberie paris", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plombier chauffagiste"],
["tarifs plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.urgence-plombier-electricien.fr/", "sos plomberie"],
["plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["apprentissage plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["cap plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.sos-plombier-discount.fr/", "sos plombier paris"],
["http://www.urgence-plombier-electricien.fr/", "electricien plombier"],
["plombier urgent paris", "http://plombiers-paris-75.fr/"],
["plombier honnete paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.jcomjeune.com/article-metier/plombier", "metier de plombier"],
["plombier chaufagiste", "https://fr.wikipedia.org/wiki/Plombier"],
["bac pro plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "devis plombier paris"],
["plombier paris 01", "http://plombiers-paris-75.fr/"],
["paris plombier", "http://plombiers-paris-75.fr/"],
["cap plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier issy les moulineaux", "http://berthier-plombier-issy-les-moulineaux-92130.fr/"],
["metier de plombier salaire", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire plombier a son compte"],
["http://www.jcomjeune.com/article-metier/plombier", "metier plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "installation sanitaire plomberie"],
["http://fecamp-services.com/plombier-paris/depannage", "travaux plombier"],
["urgence electricien", "http://www.urgence-plombier-electricien.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier urgent paris"],
["bep plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.jcomjeune.com/article-metier/plombier", "plombier"],
["http://www.urgence-plombier-electricien.fr/", "urgence dépannage"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris 75012"],
["http://www.atelier-des-artisans.com/", "dépannage paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "le metier de plombier"],
["formation plomberie lyon", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier.fr", "http://www.annuaire-plombiers.com/"],
["plombier pas chere", "http://www.sos-plombier-discount.fr/"],
["plombier à nantes", "http://www.zeplombier.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier urgence paris"],
["http://www.jcomjeune.com/article-metier/plombier", "le metier de plombier"],
["tarifs plombiers", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier parisien", "http://plombiers-paris-75.fr/"],
["plombier paris", "http://www.plomberieparis.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plombier sanitaire"],
["plombier sanitair", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.urgence-plombier-electricien.fr/", "plombier urgence paris"],
["http://www.urgence-plombier-electricien.fr/", "dépannage plomberie"],
["plombier en urgence", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "paris plomberie"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire moyen d un plombier"],
["http://www.urgence-plombier-electricien.fr/", "dépannage plomberie paris"],
["dépannage plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["bon plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.plombierparis-75.com/", "plombier pas cher paris"],
["http://www.jcomjeune.com/article-metier/plombier", "etude plomberie"],
["http://www.plomberieparis.fr/", "plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier pas cher paris"],
["plombier sur", "https://fr.wikipedia.org/wiki/Plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "service plomberie"],
["plomberie discount", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "plombier depannage"],
["https://fr.wikipedia.org/wiki/Plombier", "outillage plombier chauffagiste"],
["http://plombiers-paris-75.fr/", "intervention plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "apprentie plombier"],
["plombiers", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.urgence-plombier-electricien.fr/", "plombier electricien"],
["bac pro plomberie chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.prat-plombier-chauffagiste-69.com/", "plomberie du rhone"],
["devis plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["paris plomberie", "http://www.sos-plombier-discount.fr/"],
["http://www.annuaire-plombiers.com/", "plombier"],
["fiche plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "meilleur plombier paris"],
["formation de plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier depannage", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier sanitaire", "https://fr.wikipedia.org/wiki/Plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier paris 01"],
["plombier en urgence", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.plombier-31.fr/", "plombier 31"],
["paris plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier depannage paris", "http://www.urgence-plombier-electricien.fr/"],
["plombier", "http://www.atelier-des-artisans.com/"],
["tarif plombier paris", "http://www.sos-plombier-discount.fr/"],
["plombier dimanche", "http://www.sos-plombier-discount.fr/"],
["plomberie paris", "http://www.urgence-plombier-electricien.fr/"],
["http://plombiers-paris-75.fr/", "plombier de nuit paris"],
["http://fecamp-services.com/plombier-paris/depannage", "urgence plomberie"],
["http://www.urgence-plombier-electricien.fr/", "urgence electricien paris"],
["http://www.urgence-plombier-electricien.fr/", "plomberie depannage"],
["http://www.sos-plombier-discount.fr/", "plombier urgence paris"],
["http://plombiers-paris-75.fr/", "plombier paris urgence"],
["intervention plombier", "http://plombiers-paris-75.fr/"],
["metier plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "lycée professionnel plomberie"],
["plomberie paris", "http://plombiers-paris-75.fr/"],
["http://www.plomberieparis.fr/", "plombier a paris"],
["plombier.com", "http://www.annuaire-plombiers.com/"],
["plombiers", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier toulouse", "http://www.plombier-toulouse-ath.com/"],
["http://www.urgence-plombier-electricien.fr/", "urgence electricien"],
["métier plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.urgence-plombier-electricien.fr/", "tarif depannage electrique"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plombier nantes"],
["artisans plombiers", "http://www.atelier-des-artisans.com/"],
["http://www.jcomjeune.com/article-metier/plombier", "formation plombier"],
["plombier à", "http://www.pagesjaunes.fr/activites/plombier.html"],
["http://www.annuaire-plombiers.com/", "plombiers"],
["http://www.urgence-plombier-electricien.fr/", "plombier dépannage"],
["http://www.atelier-des-artisans.com/", "travaux de plomberie paris"],
["plombier dépannage", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "métier de plombier"],
["etude plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["formation pour devenir plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "le plombier"],
["plomberie paris 12", "http://fecamp-services.com/plombier-paris/depannage"],
["depannage plomberie paris", "http://www.sos-plombier-discount.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier honnete paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap de plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "ecole plomberie"],
["plombier depannage paris", "http://www.atelier-des-artisans.com/"],
["http://plombiers-paris-75.fr/", "plombier urgent paris"],
["plombier pgn", "http://www.pagesjaunes.fr/activites/plombier.html"],
["plombier sur paris", "http://plombiers-paris-75.fr/"],
["http://www.prat-plombier-chauffagiste-69.com/", "chauffagiste plombier"],
["plombier urgence paris", "http://www.sos-plombier-discount.fr/"],
["http://www.zeplombier.fr/", "plombier.fr"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "stage plombier chauffagiste"],
["http://www.plombierparis-75.com/", "plombier paris 75"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bp plomberie"],
["https://fr.wikipedia.org/wiki/Plombier", "eau chaude sanitaire définition"],
["http://www.urgence-plombier-electricien.fr/", "plombier depannage paris"],
["trouver plombier", "http://www.pagesjaunes.fr/activites/plombier.html"],
["plombier paris 12", "http://fecamp-services.com/plombier-paris/depannage"],
["un plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plomberie"],
["eau chaude sanitaire définition", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.sos-plombier-discount.fr/", "plombier paris"],
["http://www.urgence-plombier-electricien.fr/", "plombier sos"],
["http://www.plombierparis-75.com/", "plombier dans paris"],
["http://fecamp-services.com/plombier-paris/depannage", "depannage plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "tarif plombier paris"],
["plombier urgent", "http://www.sos-plombier-discount.fr/"],
["formation plomberie chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["prix plombier paris", "http://www.sos-plombier-discount.fr/"],
["plomberie à paris", "http://fecamp-services.com/plombier-paris/depannage"],
["trouver un plombier", "http://www.pagesjaunes.fr/activites/plombier.html"],
["plombier", "http://www.plomberieparis.fr/"],
["plombier paris", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "urgence plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bts plombier"],
["http://www.plomberieparis.fr/", "plombier dans paris"],
["plombier urgent paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.zeplombier.fr/", "plombier nantes"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "metier plombier"],
["http://www.sos-plombier-discount.fr/", "depannage plomberie paris"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire plombier"],
["plombier 12eme", "http://fecamp-services.com/plombier-paris/depannage"],
["prix plombier paris", "http://plombiers-paris-75.fr/"],
["plombier pas cher paris", "http://www.plombierparis-75.com/"],
["plomberie sanitaire video", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["sos plombier", "http://www.urgence-plombier-electricien.fr/"],
["métier de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["cap plomberie lyon", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier sur paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "metier de plombier salaire"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "stage de plombier"],
["plombier urgence", "http://www.urgence-plombier-electricien.fr/"],
["plombier", "http://www.plombier-toulouse-ath.com/"],
["http://www.plombierparis-75.com/", "plombier sur paris"],
["plombier", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "tarifs plombiers"],
["dépannage plomberie", "http://www.urgence-plombier-electricien.fr/"],
["http://www.urgence-plombier-electricien.fr/", "urgence eau paris"],
["plombier 62", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["travaux de plomberie paris", "http://www.atelier-des-artisans.com/"],
["plombier salaire", "http://www.jcomjeune.com/article-metier/plombier"],
["ecole de plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["salaire plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier dordogne"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "métier plombier chauffagiste"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier chauffage"],
["le metier de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.plombier-toulouse-ath.com/", "plombier"],
["http://www.urgence-plombier-electricien.fr/", "electricien.fr"],
["plomberie dépannage", "http://www.urgence-plombier-electricien.fr/"],
["urgence plombier", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plombier en alternance"],
["http://fecamp-services.com/plombier-paris/depannage", "depannage plombier paris"],
["plomberie paris", "http://www.atelier-des-artisans.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier dimanche"],
["sos plombier paris", "http://www.urgence-plombier-electricien.fr/"],
["recherche plombier paris", "http://plombiers-paris-75.fr/"],
["http://www.sos-plombier-discount.fr/", "plomberie urgence"],
["plomberie toulouse", "http://www.plombier-toulouse-ath.com/"],
["plombier à paris", "http://fecamp-services.com/plombier-paris/depannage"],
["pub plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "urgence eau paris"],
["plomberie paris", "http://berthier-plombier.fr/"],
["définition de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bac pro plomberie"],
["http://plombiers-paris-75.fr/", "plombier sur"],
["https://fr.wikipedia.org/wiki/Plombier", "chauffagiste sanitaire"],
["plombier chauffagiste formation", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["artisan plombier paris", "http://www.atelier-des-artisans.com/"],
["http://berthier-plombier-issy-les-moulineaux-92130.fr/", "plombier à"],
["http://www.urgence-plombier-electricien.fr/", "electricien urgence"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "salaire d un plombier chauffagiste"],
["http://berthier-plombier.fr/", "plomberie paris"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier"],
["plombier 69", "http://www.prat-plombier-chauffagiste-69.com/"],
["formation plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["chauffagiste plombier", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombiers"],
["recherche un plombier", "http://www.pagesjaunes.fr/activites/plombier.html"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier d urgence paris"],
["formation plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["cap plombier en alternance", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["fiche de poste plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["https://fr.wikipedia.org/wiki/Plombier", "metier plomberie"],
["plombier", "http://www.pagesjaunes.fr/activites/plombier.html"],
["http://www.pagesjaunes.fr/activites/plombier.html", "trouver plombier"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier chaufagiste"],
["http://www.jcomjeune.com/article-metier/plombier", "stage plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "pub plombier"],
["http://plombiers-paris-75.fr/", "plombier sur paris"],
["plombier dépannage", "http://www.urgence-plombier-electricien.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier depannage paris"],
["plombier paris urgence", "http://www.sos-plombier-discount.fr/"],
["plombier service", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier drome", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["cap plomberie toulouse", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["https://fr.wikipedia.org/wiki/Plombier", "métier plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "cout plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "bon plombier"],
["plomberie paris", "http://www.sos-plombier-discount.fr/"],
["plombier nantes", "http://www.zeplombier.fr/"],
["plombier paris urgence", "http://plombiers-paris-75.fr/"],
["plomberie chauffagiste", "https://fr.wikipedia.org/wiki/Plombier"],
["le plombier", "http://www.zeplombier.fr/"],
["http://www.atelier-des-artisans.com/", "dépannage plomberie paris"],
["urgence eau paris", "http://www.urgence-plombier-electricien.fr/"],
["métier de plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["urgence plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier paris", "http://www.plombierparis-75.com/"],
["plomberie nantes", "http://www.zeplombier.fr/"],
["http://www.urgence-plombier-electricien.fr/", "plombier urgent paris"],
["plombier sur", "http://www.pagesjaunes.fr/activites/plombier.html"],
["http://www.plombierparis-75.com/", "plombier"],
["http://www.urgence-plombier-electricien.fr/", "urgence plomberie"],
["http://www.urgence-plombier-electricien.fr/", "depannage plombier paris"],
["http://www.atelier-des-artisans.com/", "depannage plomberie paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier"],
["http://www.sos-plombier-discount.fr/", "plombier d urgence paris"],
["urgence plombier", "http://www.sos-plombier-discount.fr/"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier chauffagiste"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plombier"],
["formation de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier en urgence", "http://www.sos-plombier-discount.fr/"],
["le salaire d un plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier gaz"],
["métier plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.jcomjeune.com/article-metier/plombier", "plomberie salaire"],
["http://www.sos-plombier-discount.fr/", "plombier a paris"],
["http://www.prat-plombier-chauffagiste-69.com/", "plombier rhone"],
["le metier de plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["http://plombiers-paris-75.fr/", "plomberie à paris"],
["http://plombiers-paris-75.fr/", "artisan plombier paris 12"],
["annuaire plombier", "http://www.annuaire-plombiers.com/"],
["plombier de paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plomberie toulouse"],
["fiche plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "le metier de plombier"],
["bon plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["https://fr.wikipedia.org/wiki/Plombier", "métier plombier chauffagiste"],
["http://www.urgence-plombier-electricien.fr/", "sos electricite"],
["http://fecamp-services.com/plombier-paris/depannage", "paris depannage"],
["urgence dépannage", "http://www.urgence-plombier-electricien.fr/"],
["plombier chauffage", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://www.sos-plombier-discount.fr/", "plombier dimanche"],
["http://www.jcomjeune.com/article-metier/plombier", "plombier salaire moyen"],
["plombier.fr", "http://www.zeplombier.fr/"],
["http://plombiers-paris-75.fr/", "prix plombier paris"],
["dépannage plombier paris", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier salaire moyen", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "etude de plomberie"],
["formation plomberie", "http://www.jcomjeune.com/article-metier/plombier"],
["plombiers paris", "http://www.atelier-des-artisans.com/"],
["http://plombiers-paris-75.fr/", "urgence plombier paris"],
["http://www.jcomjeune.com/article-metier/plombier", "métier plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "bep plombier"],
["http://plombiers-paris-75.fr/", "plomberie paris"],
["https://fr.wikipedia.org/wiki/Plombier", "metier de plombier"],
["plombier", "http://www.annuaire-plombiers.com/"],
["plombier", "http://www.plombierparis-75.com/"],
["stage plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier de nuit paris"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier 62"],
["http://www.plomberieparis.fr/", "plomberie paris"],
["plombier a paris", "http://www.plombierparis-75.com/"],
["http://www.zeplombier.fr/", "plombier.com"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier sanitair"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bep plombier chauffagiste"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier de nuit"],
["http://www.sos-plombier-discount.fr/", "plomberie discount"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier"],
["bac pro plomberie en alternance", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.urgence-plombier-electricien.fr/", "plombier paris urgence"],
["depannage de plomberie", "http://www.urgence-plombier-electricien.fr/"],
["bp plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["sos plomberie", "http://www.urgence-plombier-electricien.fr/"],
["plombier dans paris", "http://www.plombierparis-75.com/"],
["cout plombier", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plombier à"],
["ecole de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.sos-plombier-discount.fr/", "urgence plomberie"],
["plombier a paris", "http://fecamp-services.com/plombier-paris/depannage"],
["artisan plombier paris 12", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.atelier-des-artisans.com/", "plombiers paris"],
["http://www.plombierparis-75.com/", "paris plombier"],
["lycée plomberie", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier sanitaire", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier de nuit paris", "http://plombiers-paris-75.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier pas chere"],
["bac pro plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["paris depannage", "http://fecamp-services.com/plombier-paris/depannage"],
["urgences plomberie", "http://www.sos-plombier-discount.fr/"],
["plombiers paris", "http://plombiers-paris-75.fr/"],
["http://plombiers-paris-75.fr/", "plombier urgence paris"],
["le metier de plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier chauffagiste", "http://www.prat-plombier-chauffagiste-69.com/"],
["http://www.jcomjeune.com/article-metier/plombier", "plombier salaire"],
["paris plomberie", "http://fecamp-services.com/plombier-paris/depannage"],
["depannage plombier", "http://www.urgence-plombier-electricien.fr/"],
["plombier.com", "http://www.zeplombier.fr/"],
["http://www.sos-plombier-discount.fr/", "plombier d urgence"],
["plombier", "http://berthier-plombier.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "formation plomberie paris"],
["dépannage paris", "http://www.atelier-des-artisans.com/"],
["http://www.sos-plombier-discount.fr/", "plombier en urgence"],
["http://www.plomberieparis.fr/", "plombier à paris"],
["sos depannage plomberie", "http://www.sos-plombier-discount.fr/"],
["plombier", "http://www.urgence-plombier-electricien.fr/"],
["plombier de nuit paris", "http://fecamp-services.com/plombier-paris/depannage"],
["sos plombier paris", "http://www.sos-plombier-discount.fr/"],
["apprentie plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["metier de plombier", "https://fr.wikipedia.org/wiki/Plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bac pro plomberie en alternance"],
["http://www.sos-plombier-discount.fr/", "devis plombier paris"],
["http://plombiers-paris-75.fr/", "depannage plombier paris"],
["http://www.jcomjeune.com/article-metier/plombier", "fiche plomberie"],
["plombier dimanche paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.sos-plombier-discount.fr/", "sos plomberie"],
["métier plombier salaire", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["www.plombier.com", "http://www.annuaire-plombiers.com/"],
["http://www.plombierparis-75.com/", "plombier à paris"],
["sos electricien", "http://www.urgence-plombier-electricien.fr/"],
["plombier depannage paris", "http://www.sos-plombier-discount.fr/"],
["plombier à paris", "http://www.plomberieparis.fr/"],
["metier de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "dépannage paris"],
["http://www.sos-plombier-discount.fr/", "plombier chauffagiste paris"],
["http://plombiers-paris-75.fr/", "plombier paris 01"],
["paris plombier", "http://www.plombierparis-75.com/"],
["cap plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.urgence-plombier-electricien.fr/", "urgence plombier paris"],
["plombier d urgence", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "plombier sanitaire"],
["urgence plomberie paris", "http://www.sos-plombier-discount.fr/"],
["http://www.urgence-plombier-electricien.fr/", "dépannage plombier paris"],
["http://www.urgence-plombier-electricien.fr/", "paris electricien"],
["plombier", "http://www.plombier-31.fr/"],
["tarifs plombier paris", "http://www.sos-plombier-discount.fr/"],
["cap plomberie paris", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plomberie paris"],
["formation plombier nantes", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "metier de plombier"],
["http://www.sos-plombier-discount.fr/", "plomberie paris"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier chaufagiste"],
["urgence plomberie", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.jcomjeune.com/article-metier/plombier", "stage de plombier"],
["http://www.pagesjaunes.fr/activites/plombier.html", "plomberie forum"],
["http://www.sos-plombier-discount.fr/", "sos depannage plomberie"],
["metier plomberie", "https://fr.wikipedia.org/wiki/Plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "plomberie chauffagiste"],
["http://berthier-plombier.fr/", "plombier"],
["plomberie salaire", "http://www.jcomjeune.com/article-metier/plombier"],
["metier plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.sos-plombier-discount.fr/", "urgence plomberie paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier urgent paris"],
["http://www.zeplombier.fr/", "plombier à nantes"],
["tarif depannage electrique", "http://www.urgence-plombier-electricien.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "bac pro plombier"],
["http://www.urgence-plombier-electricien.fr/", "plomberie urgence"],
["plombier paris", "http://plombiers-paris-75.fr/"],
["urgence plomberie", "http://www.sos-plombier-discount.fr/"],
["http://plombiers-paris-75.fr/", "plombier parisien"],
["https://fr.wikipedia.org/wiki/Plombier", "plombier"],
["http://www.pagesjaunes.fr/activites/plombier.html", "annuaire plombier"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "bac pro plombier chauffagiste"],
["métier plombier chauffagiste", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.plombierparis-75.com/", "plombier pas chere"],
["http://www.atelier-des-artisans.com/", "plombier paris"],
["plomberie urgence", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier d urgence paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.sos-plombier-discount.fr/", "plombier depannage paris"],
["http://www.plombier-toulouse-ath.com/", "plombier toulouse"],
["plombier wikipedia", "https://fr.wikipedia.org/wiki/Plombier"],
["plombier urgent paris", "http://www.urgence-plombier-electricien.fr/"],
["depannage plombier paris", "http://www.sos-plombier-discount.fr/"],
["plombier depannage", "http://www.urgence-plombier-electricien.fr/"],
["formation plomberie chauffage", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "ecole de plombier"],
["http://plombiers-paris-75.fr/", "urgence plomberie paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plomberie depannage"],
["http://www.jcomjeune.com/article-metier/plombier", "bac pro plomberie"],
["sos electricien paris", "http://www.urgence-plombier-electricien.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "formation plomberie sanitaire"],
["http://plombiers-paris-75.fr/", "paris plombier"],
["http://www.jcomjeune.com/article-metier/plombier", "profession plombier"],
["fiche rome plombier", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["métier plombier salaire", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier à", "http://berthier-plombier-issy-les-moulineaux-92130.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier dépannage"],
["http://www.atelier-des-artisans.com/", "artisan plomberie"],
["depannage plomberie paris", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.zeplombier.fr/", "plombier"],
["http://fecamp-services.com/plombier-paris/depannage", "plomberie paris 12"],
["http://www.sos-plombier-discount.fr/", "plombier"],
["https://fr.wikipedia.org/wiki/Plombier", "chauffagiste plombier"],
["plombier paris pas cher", "http://fecamp-services.com/plombier-paris/depannage"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "fiche metier plombier chauffagiste"],
["service plomberie", "http://fecamp-services.com/plombier-paris/depannage"],
["plombier de paris", "http://www.plomberieparis.fr/"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "metier plomberie"],
["http://www.jcomjeune.com/article-metier/plombier", "metier de plombier salaire"],
["http://www.jcomjeune.com/article-metier/plombier", "formation pour devenir plombier"],
["dépannage plombier paris", "http://www.sos-plombier-discount.fr/"],
["http://www.e-plombier.com/", "plombier.com"],
["http://www.zeplombier.fr/", "le plombier"],
["plombier", "http://www.pagesjaunes.fr/annuaire/voiron-38/plombiers"],
["http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere", "cap plomberie chauffagiste"],
["http://www.jcomjeune.com/article-metier/plombier", "salaire plomberie"],
["http://plombiers-paris-75.fr/", "electricien paris 10"],
["travail plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.plomberieparis.fr/", "plombier de paris"],
["salaire moyen d un plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["plombier chauffagiste paris", "http://www.sos-plombier-discount.fr/"],
["http://fecamp-services.com/plombier-paris/depannage", "urgence plombier paris"],
["diplome de plombier", "http://www.jcomjeune.com/article-metier/plombier"],
["http://www.sos-plombier-discount.fr/", "plombier de paris"],
["plombier urgent", "http://www.urgence-plombier-electricien.fr/"],
["http://www.jcomjeune.com/article-metier/plombier", "travail plombier"],
["http://www.urgence-plombier-electricien.fr/", "dépannage paris"],
["plombier", "http://www.zeplombier.fr/"],
["dépannage plombier paris", "http://www.urgence-plombier-electricien.fr/"],
["metier de plombier salaire", "http://www.onisep.fr/Ressources/Univers-Metier/Metiers/plombier-iere"],
["plombier.fr", "http://www.pagesjaunes.fr/activites/plombier.html"],
["http://www.sos-plombier-discount.fr/", "depannage plombier paris"],
["http://www.urgence-plombier-electricien.fr/", "urgence plomberie paris"],
["http://www.urgence-plombier-electricien.fr/", "plombier paris"],
["http://fecamp-services.com/plombier-paris/depannage", "plombier pas chere"],
["http://fecamp-services.com/plombier-paris/depannage", "paris plombier"]]


kw = set()
for i in l:
    for j in i:
        if j and not j.startswith('http'):
            kw.add(j)

words = np.array(list(kw))

(dim,) = words.shape

f = lambda (x,y): -leven.distance(x,y)

res=np.fromiter(itertools.imap(f, itertools.product(words, words)), dtype=np.uint8)
A = np.reshape(res,(dim,dim))

af = AffinityPropagation().fit(A)
cluster_centers_indices = af.cluster_centers_indices_
labels = af.labels_

unique_labels = set(labels)
for i in unique_labels:
    print words[labels==i]


print "calculating distances..."

(dim,) = words.shape

f = lambda (x,y): leven.distance(x,y)
res=np.fromiter(itertools.imap(f, itertools.product(words, words)),
                dtype=np.uint8)
A = np.reshape(res,(dim,dim))

print "svd..."

u,s,v = lin.svd(A, full_matrices=False)

print u.shape
print s.shape
print s
print v.shape

data = u[:,0:10]
k=KMeans(init='k-means++', k=30, n_init=10)
k.fit(data)
centroids = k.cluster_centers_
labels = k.labels_
print labels

for i in range(np.max(labels)):
    print words[labels==i]

def dist(x,y):
    return np.sqrt(np.sum((x-y)**2, axis=1))

print '#'*30
print "centroid points.."
print len(centroids)

for i,c in enumerate(centroids):
    idx = np.argmin(dist(c,data[labels==i]))
    print words[labels==i][idx]
    print words[labels==i]

